### ISSUE TITLE
not open xip.io

### ISSUE THREAD

**Issue by aogg** [peterhellberg/xip.name#9]

**Comment by peterhellberg** [comment]
What I believe this issue was opened due to is not being able to reach the original service this was inspired by (https://xip.io). What might have happened is that they decided to shut down the service. 

(I have no insight into that, I do however consider shutting down xip.name since Google has marked the domain as suspicious due to how it allows you to point it to any IP address, for example Cloudflare: http://1.1.1.1.xip.name, making them classify it as "Social engineering content")
